<template>
   <div>
    <div class="d-flex flex-column justify-center align-center">
    <h1 class="align-self-start">username</h1>
    <div class="itemtable">
  <v-data-table
    :headers="headers"
    :items="itemsufDetails"
    item-key="dc_id"
    class="elevation-1"
  ></v-data-table>
  </div>
  </div>
    </div>
</template>
<script>

export default{
    name:"itemsuf",
    data:()=>({
        itemsufDetails:[
            {
		"dc_id": 345,
		"item": 100105673,
		"item_desc": "Sprouts Cowpea",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Pre-pack",
		"subclass_name": "Sprouts",
		"standard_uom": "Each",
		"each_to_tw": 0.2,
		"suf": 26,
		"suf_status": "non-SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100087678,
		"item_desc": "Sprouts Green Gram.",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Pre-pack",
		"subclass_name": "Sprouts",
		"standard_uom": "Each",
		"each_to_tw": 0.2,
		"suf": 26,
		"suf_status": "non-SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100105654,
		"item_desc": "Sprouts Horsegram.",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Pre-pack",
		"subclass_name": "Sprouts",
		"standard_uom": "Each",
		"each_to_tw": 0.2,
		"suf": 26,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100065537,
		"item_desc": "Sprouts Channa.",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Pre-pack",
		"subclass_name": "Sprouts",
		"standard_uom": "Each",
		"each_to_tw": 0.2,
		"suf": 26,
		"suf_status": "non-SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100175449,
		"item_desc": "KIWI IMPORTED PREMUIM EA",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Major imported",
		"subclass_name": "Kiwi",
		"standard_uom": "Each",
		"each_to_tw": 0.08,
		"suf": 25,
		"suf_status": "non-SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100736505,
		"item_desc": "Dragon Fruit Nos",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Small imported",
		"subclass_name": "Others Imported Fruit",
		"standard_uom": "Each",
		"each_to_tw": 0.7,
		"suf": 6,
		"suf_status": "non-SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100597086,
		"item_desc": "Britannia Brown Bread 400 Gm Pouch",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Sandwich Bread",
		"subclass_name": "Brown Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.4,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100091388,
		"item_desc": "More fresh white Pizza Base 180gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Pizza Base",
		"subclass_name": "White Pizza base",
		"standard_uom": "Each",
		"each_to_tw": 0.18,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100115940,
		"item_desc": "Aavin Blue Fresh Milk 500 Ml Pouch",
		"division_name": "BDF",
		"department_name": "Frozen & Dairy",
		"family_name": "Short Life Dairy",
		"class_name": "Milk",
		"subclass_name": "Toned Milk",
		"standard_uom": "Each",
		"each_to_tw": 0.5,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S4",
		"crate_weight_kg": 6.5,
		"crate_vol_cft": 3.544921875
	},{
		"dc_id": 345,
		"item": 101865248,
		"item_desc": "Cavins Fresh Cow Milk 500 ml Pet Bottle",
		"division_name": "BDF",
		"department_name": "Frozen & Dairy",
		"family_name": "Short Life Dairy",
		"class_name": "Milk",
		"subclass_name": "Cow Milk",
		"standard_uom": "Each",
		"each_to_tw": 0.5,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S4",
		"crate_weight_kg": 6.5,
		"crate_vol_cft": 3.544921875
	},{
		"dc_id": 345,
		"item": 100057388,
		"item_desc": "Arokya Standardized Fresh Milk 500 Ml Pouch",
		"division_name": "BDF",
		"department_name": "Frozen & Dairy",
		"family_name": "Short Life Dairy",
		"class_name": "Milk",
		"subclass_name": "Toned Milk",
		"standard_uom": "Each",
		"each_to_tw": 0.5,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S4",
		"crate_weight_kg": 6.5,
		"crate_vol_cft": 3.544921875
	},{
		"dc_id": 345,
		"item": 100044689,
		"item_desc": "Modern Multigrain Superseed 400 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Multigrain Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.4,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100142281,
		"item_desc": "Britannia Bread 100% WholeWheat 450 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Whole Wheat Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.45,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100230204,
		"item_desc": "Fresh Baked Atta Pizza Base",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Pizza Base",
		"subclass_name": "Brown pizza base",
		"standard_uom": "Each",
		"each_to_tw": 0.4,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100141114,
		"item_desc": "More Q 1st Masala Kulcha Bread 200 gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Kulcha",
		"standard_uom": "Each",
		"each_to_tw": 0.2,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100141415,
		"item_desc": "More Q 1st Atta Bread 400 gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Sandwich Bread",
		"subclass_name": "Atta Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.4,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100485186,
		"item_desc": "Fresh Baked Whole Wheat Bread 400 gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Whole Wheat Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.4,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 101932527,
		"item_desc": "Cavins H-Curd 450 gm Pouch",
		"division_name": "BDF",
		"department_name": "Frozen & Dairy",
		"family_name": "Short Life Dairy",
		"class_name": "Curd & Dahi",
		"subclass_name": "Pouch Plain Curd",
		"standard_uom": "Each",
		"each_to_tw": 0.45,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100115942,
		"item_desc": "Aavin Green Fresh Milk 500 Ml Pouch",
		"division_name": "BDF",
		"department_name": "Frozen & Dairy",
		"family_name": "Short Life Dairy",
		"class_name": "Milk",
		"subclass_name": "Standardized Milk",
		"standard_uom": "Each",
		"each_to_tw": 0.5,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S4",
		"crate_weight_kg": 6.5,
		"crate_vol_cft": 3.544921875
	},{
		"dc_id": 345,
		"item": 100073186,
		"item_desc": "More fresh Ladi Pav 180gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Rolls Buns & Pav",
		"subclass_name": "Pav",
		"standard_uom": "Each",
		"each_to_tw": 0.18,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100230262,
		"item_desc": "Fresh Baked Fruit Buns 150 gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Rolls Buns & Pav",
		"subclass_name": "Other Buns",
		"standard_uom": "Each",
		"each_to_tw": 0.15,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100157103,
		"item_desc": "Fresh Baked Brown Bread 400 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Sandwich Bread",
		"subclass_name": "Brown Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.4,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100157138,
		"item_desc": "Fresh Baked Multi Grain Bread 200 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Multigrain Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.2,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100157126,
		"item_desc": "Fresh Baked Masala Bread 400 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Flavoured Breads",
		"standard_uom": "Each",
		"each_to_tw": 0.4,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100128593,
		"item_desc": "Heritage Pouch Curd 450 gm.",
		"division_name": "BDF",
		"department_name": "Frozen & Dairy",
		"family_name": "Short Life Dairy",
		"class_name": "Curd & Dahi",
		"subclass_name": "Pouch Plain Curd",
		"standard_uom": "Each",
		"each_to_tw": 0.45,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100066597,
		"item_desc": "Modern 100% Whole Wheat 400 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Whole Wheat Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.4,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100110190,
		"item_desc": "Heritage Toned Fresh Milk 500 Ml Pouch.",
		"division_name": "BDF",
		"department_name": "Frozen & Dairy",
		"family_name": "Short Life Dairy",
		"class_name": "Milk",
		"subclass_name": "Toned Milk",
		"standard_uom": "Each",
		"each_to_tw": 0.5,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S4",
		"crate_weight_kg": 6.5,
		"crate_vol_cft": 3.544921875
	},{
		"dc_id": 345,
		"item": 100213637,
		"item_desc": "Jersey Full Cream Milk 500 Ml Pouch",
		"division_name": "BDF",
		"department_name": "Frozen & Dairy",
		"family_name": "Short Life Dairy",
		"class_name": "Milk",
		"subclass_name": "Full Cream Milk",
		"standard_uom": "Each",
		"each_to_tw": 0.5,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S4",
		"crate_weight_kg": 6.5,
		"crate_vol_cft": 3.544921875
	},{
		"dc_id": 345,
		"item": 100157120,
		"item_desc": "Fresh Baked Jumbo Sandwich Bread 800 Gm.",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Sandwich Bread",
		"subclass_name": "White Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.8,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100815216,
		"item_desc": "More Fresh Olive Foccacia Bread1 nos Pouch",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Other specialty Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.45,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100630887,
		"item_desc": "Fresh Baked White Bread 200 Gm.",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Sandwich Bread",
		"subclass_name": "White Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.2,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100157105,
		"item_desc": "Fresh Baked Multi Grain Bread 400 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Multigrain Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.4,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100157118,
		"item_desc": "Fresh Baked Fruit Bread 400 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Fruit Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.4,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100157142,
		"item_desc": "Fresh Baked Atta Bread 200 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Sandwich Bread",
		"subclass_name": "Atta Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.2,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 101369317,
		"item_desc": "More 100% whole wheat bread 400 gm Pouch",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Whole Wheat Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.4,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100134207,
		"item_desc": "Jersey Fresh Toned Milk 500ml Pouch",
		"division_name": "BDF",
		"department_name": "Frozen & Dairy",
		"family_name": "Short Life Dairy",
		"class_name": "Milk",
		"subclass_name": "Toned Milk",
		"standard_uom": "Each",
		"each_to_tw": 0.5,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S4",
		"crate_weight_kg": 6.5,
		"crate_vol_cft": 3.544921875
	},{
		"dc_id": 345,
		"item": 100157100,
		"item_desc": "Fresh Baked White Bread 400 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Sandwich Bread",
		"subclass_name": "White Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.4,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 101083329,
		"item_desc": "Modern Bread100% whole wheat Chapathi450 gm Pouch",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Indian Flat Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.45,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100214905,
		"item_desc": "Fresh Baked Milk Bread. 400 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Sandwich Bread",
		"subclass_name": "Milk Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.4,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100038127,
		"item_desc": "Modern Bread Sandwich Supreme 450 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Sandwich Bread",
		"subclass_name": "White Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.45,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 101836050,
		"item_desc": "Modern Bread Poori 200 gm Pack",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Indian Flat Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.2,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100157147,
		"item_desc": "Fresh Baked Fruit Bread 200 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Fruit Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.2,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 101486563,
		"item_desc": "More fresh Burger Bun 130 gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Rolls Buns & Pav",
		"subclass_name": "Burger Bun",
		"standard_uom": "Each",
		"each_to_tw": 0.13,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100065415,
		"item_desc": "Britannia Bread Sweet 600 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Sandwich Bread",
		"subclass_name": "White Bread",
		"standard_uom": "Each",
		"each_to_tw": 0.6,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100157116,
		"item_desc": "Fresh Baked Garlic Bread 400 Gm",
		"division_name": "BDF",
		"department_name": "Bakery",
		"family_name": "Bread",
		"class_name": "Specialty Breads",
		"subclass_name": "Flavoured Breads",
		"standard_uom": "Each",
		"each_to_tw": 0.4,
		"suf": 1,
		"suf_status": "non-SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100005625,
		"item_desc": "White Egg Loose",
		"division_name": "Fresh",
		"department_name": "Eggs",
		"family_name": "Economy Eggs",
		"class_name": "Chicken Eggs",
		"subclass_name": "White Chicken Eggs",
		"standard_uom": "Each",
		"each_to_tw": 0.07,
		"suf": 150,
		"suf_status": "SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100053750,
		"item_desc": "Drumstick",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "Each",
		"each_to_tw": 0.1,
		"suf": 20,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100139106,
		"item_desc": "Water Melon Kiran",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Melon",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 20,
		"suf_status": "SUF",
		"crate type": "Bag",
		"crate_weight_kg": 1,
		"crate_vol_cft": 0.706293334
	},{
		"dc_id": 345,
		"item": 100007398,
		"item_desc": "Watermelon Striped",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Seasonal",
		"subclass_name": "Seasonal Melon",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 20,
		"suf_status": "SUF",
		"crate type": "Bag",
		"crate_weight_kg": 1,
		"crate_vol_cft": 0.706293334
	},{
		"dc_id": 345,
		"item": 100113011,
		"item_desc": "ONION LOOSE KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "POT",
		"subclass_name": "Onion",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 20,
		"suf_status": "SUF",
		"crate type": "Bag",
		"crate_weight_kg": 1,
		"crate_vol_cft": 0.706293334
	},{
		"dc_id": 345,
		"item": 100137101,
		"item_desc": "Coriander leaves",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Leafy",
		"standard_uom": "Each",
		"each_to_tw": 0.25,
		"suf": 15,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100053494,
		"item_desc": "Coconut",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Non -Freshness Relavant",
		"subclass_name": "Others Hard Vegetables",
		"standard_uom": "Each",
		"each_to_tw": 0.52,
		"suf": 15,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100137872,
		"item_desc": "Mint Leaves",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Leafy",
		"standard_uom": "Each",
		"each_to_tw": 0.25,
		"suf": 12,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 101336619,
		"item_desc": "PEAR VERMONT BEAUTY (GREEN) KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Small imported",
		"subclass_name": "Pears Imported",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 12,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100005165,
		"item_desc": "Potato Economy",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "POT",
		"subclass_name": "Potato",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 12,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100113310,
		"item_desc": "Tomato Local",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "POT",
		"subclass_name": "Tomato",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 12,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100595994,
		"item_desc": "A/ Sweetcorn",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "Each",
		"each_to_tw": 0.25,
		"suf": 10,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100048395,
		"item_desc": "Poultry Chicken Eggs Pack of 6.",
		"division_name": "Fresh",
		"department_name": "Eggs",
		"family_name": "Economy Eggs",
		"class_name": "Chicken Eggs",
		"subclass_name": "White Chicken Eggs",
		"standard_uom": "Each",
		"each_to_tw": 0.45,
		"suf": 10,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100112780,
		"item_desc": "STRAWBERRY PKD EA",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Seasonal",
		"subclass_name": "Strawberry",
		"standard_uom": "Each",
		"each_to_tw": 0.2,
		"suf": 10,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100137514,
		"item_desc": "Curry Leaves",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Leafy",
		"standard_uom": "Each",
		"each_to_tw": 0.1,
		"suf": 10,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100112827,
		"item_desc": "Mushroom Button",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Regular Exotics",
		"subclass_name": "Class A",
		"standard_uom": "Each",
		"each_to_tw": 0.2,
		"suf": 12,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100074866,
		"item_desc": "Sweet Corn.",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "Each",
		"each_to_tw": 0.35,
		"suf": 10,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100113109,
		"item_desc": "ORANGE NAGPUR KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Seasonal",
		"subclass_name": "Orange Indian",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 10,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100113205,
		"item_desc": "Tomato Standard",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "POT",
		"subclass_name": "Tomato",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 10,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100175414,
		"item_desc": "APPLE SHIMLA KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Seasonal",
		"subclass_name": "Indian Apple",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 10,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100113213,
		"item_desc": "ORANGE KINNOW KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Seasonal",
		"subclass_name": "Orange Indian",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 10,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100194743,
		"item_desc": "Fig Premium",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Seasonal",
		"subclass_name": "Other Seasonl Fruit",
		"standard_uom": "Each",
		"each_to_tw": 0.2,
		"suf": 8,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100136888,
		"item_desc": "Banana Yallaki",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Banana - Others",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 8,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100052455,
		"item_desc": "Cucumber Hybrid",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 8,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100821697,
		"item_desc": "poongani Green Leaf",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Leafy",
		"standard_uom": "Each",
		"each_to_tw": 0.25,
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100078856,
		"item_desc": "Gongura Bunch",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "Each",
		"each_to_tw": 0.25,
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100821701,
		"item_desc": "Siru Leaf",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Leafy",
		"standard_uom": "Each",
		"each_to_tw": 0.25,
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100152386,
		"item_desc": "Pineapple Raja",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Other Regular Fruits",
		"standard_uom": "Each",
		"each_to_tw": 1.2,
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100821691,
		"item_desc": "Manthakali Leaf",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Leafy",
		"standard_uom": "Each",
		"each_to_tw": 0.25,
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100136984,
		"item_desc": "Amaranthus Green",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Leafy",
		"standard_uom": "Each",
		"each_to_tw": 0.25,
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100137397,
		"item_desc": "Palak",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Leafy",
		"standard_uom": "Each",
		"each_to_tw": 0.35,
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100005468,
		"item_desc": "Cauliflower",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "Each",
		"each_to_tw": 0.5,
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100048964,
		"item_desc": "Spring Onion Leaves",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Leafy",
		"standard_uom": "Each",
		"each_to_tw": 0.25,
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100803742,
		"item_desc": "Grapes SuperSonaka Seedless",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Seasonal",
		"subclass_name": "Grapes Indian",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100052560,
		"item_desc": "Poovan Banana",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Banana - Others",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100113184,
		"item_desc": "ORANGE IMPORTED KG (VALENCIA)",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Small imported",
		"subclass_name": "Orange Imported",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100052458,
		"item_desc": "Elephant Foot Yam Slice",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Cut",
		"subclass_name": "Regular Cut",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100007396,
		"item_desc": "APPLE RED DELICIOUS USA KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Major imported",
		"subclass_name": "Imported Apple",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100112851,
		"item_desc": "GRAPES SHARAD SEEDLESS KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Seasonal",
		"subclass_name": "Grapes Indian",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100113521,
		"item_desc": "Cabbage",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100052373,
		"item_desc": "Sweet Orange",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Other Regular Fruits",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100052568,
		"item_desc": "Banana Red.",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Banana - Others",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100112798,
		"item_desc": "GRAPES RED GLOBE KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Small imported",
		"subclass_name": "Grapes Imported",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100113272,
		"item_desc": "Papaya",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Papaya",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100112296,
		"item_desc": "Carrot Local",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Regular",
		"subclass_name": "Regular Carrots Red",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100136802,
		"item_desc": "Banana Nendran",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Banana - Others",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100052453,
		"item_desc": "Sambar Onion",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100112350,
		"item_desc": "Banana Robusta",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Banana - Robusta",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100112878,
		"item_desc": "Musk Melon",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Melon",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100112093,
		"item_desc": "Lemon",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 5,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100113256,
		"item_desc": "Bottle Gourd",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Guards",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 5,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100153266,
		"item_desc": "Tapioca",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Non -Freshness Relavant",
		"subclass_name": "Others Hard Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 5,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100005100,
		"item_desc": "Ash Gourd.",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Guards",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 5,
		"suf_status": "SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100113002,
		"item_desc": "Green Peas",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Sesaonal Vegetables",
		"subclass_name": "Green Peas",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 5,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100052464,
		"item_desc": "PumPkin Green Slice",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Cut",
		"subclass_name": "Regular Cut",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 5,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100685309,
		"item_desc": "Guava Packed",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Other Regular Fruits",
		"standard_uom": "Each",
		"each_to_tw": 1,
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100084697,
		"item_desc": "Banana Stem",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "Each",
		"each_to_tw": 0.6,
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100137194,
		"item_desc": "Brinjal Purple Long",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Brinjals",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100367795,
		"item_desc": "Guava Premium",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Other Regular Fruits",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100137629,
		"item_desc": "Coccinia.",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100112835,
		"item_desc": "Beet Root",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100052656,
		"item_desc": "Chow Chow",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100112384,
		"item_desc": "Ridge Gourd",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Guards",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 101821553,
		"item_desc": "GARLIC LOOSE KG(40 TO 45 MM)",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Organics",
		"subclass_name": "Organic Fruit",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100052645,
		"item_desc": "Brinjal Varikathri.",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Brinjals",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100007394,
		"item_desc": "APPLE GRANNY SMITH KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Major imported",
		"subclass_name": "Imported Apple",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100085115,
		"item_desc": "English Cucumber",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100005506,
		"item_desc": "Potato Baby",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "POT",
		"subclass_name": "Potato",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100113660,
		"item_desc": "Carrot Ooty.",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Regular",
		"subclass_name": "Regular Carrots Red",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100011289,
		"item_desc": "Baby Corn Unpeeled",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Regular Exotics",
		"subclass_name": "Class A",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 3,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100136706,
		"item_desc": "Radish White",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100112915,
		"item_desc": "Okra",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100113580,
		"item_desc": "Capsicum Green",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100111779,
		"item_desc": "Chilli Green.",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Chilly",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100111912,
		"item_desc": "Colacasia",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Non -Freshness Relavant",
		"subclass_name": "Others Hard Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100052475,
		"item_desc": "Raw Banana Local",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100052621,
		"item_desc": "Beans Chikadi",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Beans",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100112481,
		"item_desc": "Sapota",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Other Regular Fruits",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100112991,
		"item_desc": "Sweet Potato",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Non -Freshness Relavant",
		"subclass_name": "Others Hard Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100175756,
		"item_desc": "Knol Khol",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100111963,
		"item_desc": "Amla",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100068108,
		"item_desc": "Banana Flower",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "Each",
		"each_to_tw": 0.5,
		"suf": 3,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100052467,
		"item_desc": "Snakegourd Small",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Guards",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 3,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100112069,
		"item_desc": "PumPkin Disco",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Non -Freshness Relavant",
		"subclass_name": "Others Hard Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 3,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100137573,
		"item_desc": "GUAVA THAI KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Small imported",
		"subclass_name": "Thai Fruits",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 3,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100052670,
		"item_desc": "Butter Fruit",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Regular Exotics",
		"subclass_name": "Class A",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 3,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100113336,
		"item_desc": "Brinjal Black Big Bharta",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Brinjals",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 3,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100113563,
		"item_desc": "Cabbage Red",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Regular Exotics",
		"subclass_name": "Class A",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 3,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100113125,
		"item_desc": "Bitter Gourd",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Guards",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 3,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100052700,
		"item_desc": "Banana Karpooravalli",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Banana - Others",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 3,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100112211,
		"item_desc": "MANGO RAW KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Others soft Vegetables",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 3,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100112632,
		"item_desc": "Beans French.",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Beans",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 3,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100052667,
		"item_desc": "Bajji Chilli",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Chilly",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 2,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100113491,
		"item_desc": "Broccolli",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Regular Exotics",
		"subclass_name": "Class A",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 2,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100005045,
		"item_desc": "Brinjal Long Green",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Brinjals",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 3,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100005137,
		"item_desc": "Brinjal Purple Round",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Freshness Relevant",
		"subclass_name": "Brinjals",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100112712,
		"item_desc": "Ginger",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Non -Freshness Relavant",
		"subclass_name": "Ginger",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100111921,
		"item_desc": "POMEGRANATE BHAGWA KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Seasonal",
		"subclass_name": "Pomegranate",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100112018,
		"item_desc": "POTATO LOOSE KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "POT",
		"subclass_name": "Potato",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 12,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100112982,
		"item_desc": "Ber",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Other Regular Fruits",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100113117,
		"item_desc": "GUAVA KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Regular",
		"subclass_name": "Other Regular Fruits",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 4,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100113619,
		"item_desc": "Capsicum Red",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Regular Exotics",
		"subclass_name": "Class A",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 1,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100113635,
		"item_desc": "Capsicum Yellow",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Regular Exotics",
		"subclass_name": "Class A",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 1,
		"suf_status": "SUF",
		"crate type": "S1",
		"crate_weight_kg": 0.7,
		"crate_vol_cft": 0.508531201
	},{
		"dc_id": 345,
		"item": 100136597,
		"item_desc": "GRAPES SONAKA SEEDLESS KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Seasonal",
		"subclass_name": "Grapes Indian",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100137303,
		"item_desc": "PLUM IMPORTED KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Small imported",
		"subclass_name": "Others Imported Fruit",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 6,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100139237,
		"item_desc": "APPLE ROYAL GALA KG",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Fruit",
		"class_name": "Major imported",
		"subclass_name": "Imported Apple",
		"standard_uom": "KG",
		"each_to_tw": 1,
		"suf": 12,
		"suf_status": "non-SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100652221,
		"item_desc": "Flowers - Chamanthi Yellow.",
		"division_name": "Fresh",
		"department_name": "F&V",
		"family_name": "Vegetables",
		"class_name": "Flowers",
		"subclass_name": "Ornamental Flowers",
		"standard_uom": "KG",
		"each_to_tw": "KG",
		"suf": 3,
		"suf_status": "SUF",
		"crate type": "S2",
		"crate_weight_kg": 1.4,
		"crate_vol_cft": 1.356083202
	},{
		"dc_id": 345,
		"item": 100720085,
		"item_desc": "White Paper Bag 8 X 12",
		"division_name": "Others",
		"department_name": "Non Trading",
		"family_name": "Non Trading",
		"class_name": "Non Trading Non Merchandise",
		"subclass_name": "Non Trading Carry Bags",
		"standard_uom": "Each",
		"each_to_tw": 0.013636364,
		"suf": 1100,
		"suf_status": "SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	},{
		"dc_id": 345,
		"item": 100720089,
		"item_desc": "White Paper Bag 11 X 17",
		"division_name": "Others",
		"department_name": "Non Trading",
		"family_name": "Non Trading",
		"class_name": "Non Trading Non Merchandise",
		"subclass_name": "Non Trading Carry Bags",
		"standard_uom": "Each",
		"each_to_tw": 0.013636364,
		"suf": 1100,
		"suf_status": "SUF",
		"crate type": "S3",
		"crate_weight_kg": 2,
		"crate_vol_cft": 2.034124803
	}
],
headers: [
        {
          text: 'dc_id',
          align: 'start',
          value: 'dc_id',
        },
        {
          text: 'item',
          sortable: false,
          value: 'item',
        },
         {
          text: 'item_desc',
          sortable: false,
          value: 'item_desc',
        },
        {
          text: 'division_name',
          sortable: false,
          value: 'division_name',
        },
        {
          text: 'department_name',
          sortable: false,
          value: 'department_name',
        },
        {
          text: 'family_name',
          sortable: false,
          value: 'family_name',
        },
        {
          text: 'class_name',
          sortable: false,
          value: 'class_name',
        },
        {
          text: 'subclass_name',
          sortable: false,
          value: 'subclass_name',
        },
        {
          text: 'standard_uom',
          sortable: false,
          value: 'standard_uom',
        },
        {
          text: 'each_to_tw',
          value: 'each_to_tw',
        },
        {
          text: 'suf',
          value: 'suf',
        },
        {
          text: 'suf_status',
          sortable: false,
          value: 'suf_status',
        },
        {
          text: 'crate type',
          sortable: false,
          value: 'crate type',
        },
        {
          text: 'crate_weight_kg',
          value: 'crate_weight_kg',
        },
        {
          text: 'crate_vol_cft',
          value: 'crate_vol_cft',
        }
      ],

    })
}
</script>
<style scoped>
.itemtable{
    margin-left:50px;
    margin-right:50px;
}
</style>